/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import FileSystem.SistemaArchivos;
import FileSystem.Directorio;
import FileSystem.Archivo;
import DataStruct.LinkedList;
import DataStruct.Nodo;
import Scheduler.PlanificadorES;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class Delete extends javax.swing.JFrame {

    
    private SistemaArchivos sistema;
    private SimuladorSistArchivos mainUI;

    /**
     * Creates new form Delete
     */
    public Delete(SistemaArchivos sistema, SimuladorSistArchivos mainUI) {
        this.sistema = sistema;
        this.mainUI = mainUI;
        initComponents();
        cargarDirectoriosEnComboBox();
        configurarListeners();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
    }
    
    private void configurarListeners() {
    // Cuando cambie el directorio, actualizar los archivos
    jComboBox1.addActionListener(e -> {
        String nombreDir = (String) jComboBox1.getSelectedItem();
        if (nombreDir != null) {
            Directorio dir = buscarDirectorioPorNombreN(sistema.getRoot(), nombreDir);
            if (dir != null) {
                cargarArchivosEnComboBox(dir);
            }
        }
    });

    // Cuando se haga click en "Eliminar"
    jButton1.addActionListener(e -> eliminarArchivo());
}
    
    private void eliminarArchivo() {
    String nombreDirectorio = (String) jComboBox1.getSelectedItem();
    String nombreArchivo = (String) jComboBox2.getSelectedItem();

    if (nombreDirectorio == null || nombreArchivo == null) {
        JOptionPane.showMessageDialog(this, "Seleccione un directorio y un archivo");
        return;
    }

    Directorio dir = buscarDirectorioPorNombreN(sistema.getRoot(), nombreDirectorio);
    if (dir == null) {
        JOptionPane.showMessageDialog(this, "Directorio no encontrado");
        return;
    }

    // Crear proceso de eliminación
    sistema.crearProceso(
        "px_delete",
        "delete",
        nombreArchivo,
        0,
        dir,
        "admin",
        5
    );

    PlanificadorES planificador = new PlanificadorES(sistema);
    while (sistema.hayProcesosPendientes()) {
        planificador.ejecutarPrioridad();
    }

    // Actualizar UI principal
    if (mainUI != null) {
        mainUI.actualizarArbol();
        mainUI.llenarTablaAsignacion(sistema);
        mainUI.dibujarDisco();
    }

    // Actualizar JComboBox de archivos
    cargarArchivosEnComboBox(dir);

    JOptionPane.showMessageDialog(this, "Archivo eliminado correctamente");
}

    private void cargarDirectoriosEnComboBox() {
        jComboBox1.removeAllItems();
        listarDirectoriosRecursivo(sistema.getRoot());
    }

    public void cargarArchivosEnComboBox(Directorio dir) {
    jComboBox2.removeAllItems();
    LinkedList<Archivo> archivos = dir.getArchivos();
    for (int i = 0; i < archivos.getLength(); i++) {
        Archivo a = (Archivo) archivos.getElementIn(i); // casteo obligatorio
        jComboBox2.addItem(a.getNombre());
    }
}

    private void listarDirectoriosRecursivo(Directorio actual) {
        jComboBox1.addItem(actual.getNombre());
        Nodo<Directorio> nodo = actual.getSubdirectorios().getFirst();
        while (nodo != null) {
            listarDirectoriosRecursivo(nodo.getElement());
            nodo = nodo.getNext();
        }
    }

    private Directorio buscarDirectorioPorNombreN(Directorio actual, String nombre) {
    if (actual.getNombre().equalsIgnoreCase(nombre)) return actual;
    Nodo<Directorio> nodo = actual.getSubdirectorios().getFirst();
    while (nodo != null) {
        Directorio encontrado = buscarDirectorioPorNombreN(nodo.getElement(), nombre);
        if (encontrado != null) return encontrado;
        nodo = nodo.getNext();
    }
    return null;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Eliminar Archivo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel2.setText("Directorio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel3.setText("Archivo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
