/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Disk.Disco;
import simuladorsistemadearchivos.SimuladorSistemaDeArchivos;
import FileSystem.SistemaArchivos;
import javax.swing.JOptionPane;
import FileSystem.Directorio;
import DataStruct.LinkedList;
import DataStruct.Nodo;
import Scheduler.PlanificadorES;

/**
 *
 * @author Jose
 */
public class New extends javax.swing.JFrame {
    private SistemaArchivos sistema;
    private SimuladorSistArchivos mainUI;

    /**
     * Creates new form New
     */
    public New(SistemaArchivos sistema, SimuladorSistArchivos mainUI) {
        this.sistema = sistema;
        this.mainUI = mainUI;  
        initComponents();
         cargarDirectoriosEnComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText(" Crear Archivo ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 250, 50));

        jLabel2.setText("Tamaño Archivo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel3.setText("Directorio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setText("Nombre Archivo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jButton1.setText("Crear ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombreArchivo = jTextField1.getText();
    String tamKBStr = jTextField2.getText();
    String nombreDirectorio = (String) jComboBox1.getSelectedItem();

    if (nombreArchivo.isEmpty() || tamKBStr.isEmpty() || nombreDirectorio == null) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos");
        return;
    }

    int tamKB;
    try {
        tamKB = Integer.parseInt(tamKBStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El tamaño debe ser un número");
        return;
    }

    // buscar directorio real
    Directorio destino = buscarDirectorioPorNombreN(sistema.getRoot(), nombreDirectorio);

    if (destino == null) {
        JOptionPane.showMessageDialog(this, "No se encontró el directorio seleccionado");
        return;
    }

    int bloques = convertirATamanoBloques(tamKB);

    sistema.crearProceso(
            "px",
            "createFile",
            nombreArchivo,
            bloques,
            destino,
            "admin",
            5
    );
    
    PlanificadorES planificador = new PlanificadorES(sistema);
    while (sistema.hayProcesosPendientes()) {
        planificador.ejecutarPrioridad();
    }
    if (mainUI != null) {
        mainUI.actualizarArbol();
        mainUI.llenarTablaAsignacion(sistema);
        mainUI.dibujarDisco();
    }

    // 3️⃣ Actualizar interfaz
    cargarDirectoriosEnComboBox();

    JOptionPane.showMessageDialog(this, "Proceso creado correctamente");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New(null, null).setVisible(true);
            }
        });
    }
    
    public int convertirATamanoBloques(int tamArchivoKB) {
    int tamBloqueKB = sistema.getDisco().getTamBloqueKB();
    return (int) Math.ceil((double) tamArchivoKB / tamBloqueKB);
}
    
public void cargarDirectoriosEnComboBox() {
    jComboBox1.removeAllItems();
    listarDirectoriosRecursivo(sistema.getRoot());
}

public void listarDirectoriosRecursivo(Directorio actual) {
    jComboBox1.addItem(actual.getNombre()); // solo el nombre

    Nodo<Directorio> nodo = actual.getSubdirectorios().getFirst();

    while (nodo != null) {
        listarDirectoriosRecursivo(nodo.getElement());
        nodo = nodo.getNext();
    }
}

public Directorio buscarDirectorioPorNombreN(Directorio actual, String nombre) {

    if (actual.getNombre().equalsIgnoreCase(nombre)) {
        return actual;
    }

    Nodo<Directorio> nodo = actual.getSubdirectorios().getFirst();

    while (nodo != null) {
        Directorio encontrado = buscarDirectorioPorNombreN(nodo.getElement(), nombre);
        if (encontrado != null) return encontrado;

        nodo = nodo.getNext();
    }

    return null;
}

    
    private void recorrerDirectorios(Directorio dir) {

    // Agregar directorio actual al ComboBox
    jComboBox1.addItem(dir.getNombre());

    // Obtener la lista de subdirectorios
    LinkedList<Directorio> lista = dir.getSubdirectorios();

    Nodo<Directorio> nodo = lista.getFirst();  // primer nodo

    // Recorrer cada nodo de la lista
    while (nodo != null) {
        Directorio sub = nodo.getElement();
        recorrerDirectorios(sub);   // recursión
        nodo = nodo.getNext();      // avanzar
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
