/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import FileSystem.Archivo;
import FileSystem.Directorio;
import FileSystem.SistemaArchivos;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author vivia
 */
public class SimuladorSistArchivos extends javax.swing.JFrame {

    /**
     * Creates new form SimuladorSistArchivos
     */
    
    private SistemaArchivos sistema;
    
    public SimuladorSistArchivos(SistemaArchivos sistema) {
        initComponents();
        this.sistema = sistema;
        
        setTitle("Simulador de Sistema de Archivos");
        setSize(600, 500);
        setLocationRelativeTo(null);

        actualizarArbol();
       
    }
    
    // Construye el árbol a partir del sistema de archivos
    private void actualizarArbol() {
        Directorio rootDir = sistema.getRoot();

        // Crea el nodo raíz
        DefaultMutableTreeNode nodoRaiz = new DefaultMutableTreeNode(rootDir.getNombre());

        // Llama al método recursivo para llenar los subdirectorios
        construirArbol(nodoRaiz, rootDir);

        // Asigna el modelo al árbol
        DefaultTreeModel modelo = new DefaultTreeModel(nodoRaiz);
        arbol.setModel(modelo);
    }

    // Recorre recursivamente los directorios y archivos
    private void construirArbol(DefaultMutableTreeNode nodoPadre, Directorio dir) {
        
        // Añadir subdirectorios
        var nodoSub = dir.getSubdirectorios().getFirst();
        while (nodoSub != null) {
            Directorio sub = (Directorio) nodoSub.getElement();
            DefaultMutableTreeNode nodoDir = new DefaultMutableTreeNode(sub.getNombre());
            nodoPadre.add(nodoDir);
            construirArbol(nodoDir, sub); // recursión
            nodoSub = nodoSub.getNext();
        }

        // Añadir archivos
        var nodoArchivo = dir.getArchivos().getFirst();
        while (nodoArchivo != null) {
            Archivo a = (Archivo) nodoArchivo.getElement();
            System.out.println("LOOP ARCHIVOS");
            DefaultMutableTreeNode nodoA = new DefaultMutableTreeNode(a.getNombre());
            nodoPadre.add(nodoA);
            nodoArchivo = nodoArchivo.getNext();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(arbol);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
